_BASE_: "Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    IN_FEATURES: ["res5"]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    COMMON_STRIDE: 16
    #NUM_CLASSES: 2
    LOSS_TYPE: "hard_pixel_mining"
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
SOLVER:
  BASE_LR: 0.01
  MAX_ITER: 500
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 4
INPUT:
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATALOADER:
  NUM_WORKERS: 10